version: 2
snapshot:
  widths: [375, 768, 1280]
  min-height: 1024
  percy-css: |
    iframe { display: none; }
discovery:
  allowed-hostnames: []
  network-idle-timeout: 100
  page-pool-size-min: 1
  page-pool-size-max: 5
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: "node_modules/**/*" 