version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: logo_gallery_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=LogoGalleryDevelopmentDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped

volumes:
  mongodb_data:
    name: logo_gallery_mongodb_data 