name: CI

on:
  push:
    branches: [ main, feature/*, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Type check
      run: npm run type-check || true
    
    - name: Lint
      run: npm run lint || true
    
    - name: Build
      run: npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NEXTAUTH_URL: http://localhost:3000
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }} 